#!/bin/bash

# MySQL connection details
MYSQL_USER="root"          # MySQL username
MYSQL_PASS="password"      # MySQL password
MYSQL_HOST="localhost"     # MySQL host (change if needed)

# Database name to create
DB_NAME="alx_book_store"

# Execute the MySQL command to create the database
mysql -u $MYSQL_USER -p$MYSQL_PASS -h $MYSQL_HOST -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
